modLoader="javafml"
loaderVersion = "[40,)"
license = "Apache 2.0"

[[mods]]
modId="toolswap"
version="${file.jarVersion}"
displayName="ToolSwap"
updateJSONURL="https://assets.melanx.de/updates/automatic-tool-swap.json"
authors="MelanX"
description='''
Swaps the tools to the effective one if it's in hotbar.
'''

[[dependencies.toolswap]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
