modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="toolswap"
version="${file.jarVersion}"
displayName="ToolSwap"
logoFile="logo.png"
authors="MelanX"
description='''
Swaps the tools to the effective one if it's in hotbar.
'''
[[dependencies.toolswap]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
