modLoader="javafml"
loaderVersion="[33,)"
license="MIT License"

[[mods]]
modId="toolswap"
version="${file.jarVersion}"
displayName="ToolSwap"
logoFile="logo.png"
authors="MelanX"
description='''
Swaps the tools to the effective one if it's in hotbar.
'''

[[dependencies.toolswap]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
