modLoader="javafml"
loaderVersion = "[41,)"
license = "Apache 2.0"

[[mods]]
modId="toolswap"
version="${file.jarVersion}"
displayName="ToolSwap"
updateJSONURL="https://assets.melanx.de/updates/automatic-tool-swap.json"
authors="MelanX"
displayTest="IGNORE_ALL_VERSION"
description='''
Swaps the tools to the effective one if it's in hotbar.
'''

[[dependencies.toolswap]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"
