modLoader="javafml"
loaderVersion="[${fml},)"
license = "Apache 2.0"
issueTrackerURL="https://github.com/MelanX/ToolSwap/issues"

[[mods]]
modId="toolswap"
version="${version}"
displayName="ToolSwap"
updateJSONURL="https://assets.melanx.de/updates/automatic-tool-swap.json"
authors="MelanX"
displayTest="IGNORE_ALL_VERSION"
description='''
Swaps the tools to the effective one if it's in hotbar.
'''

[[dependencies.toolswap]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.toolswap]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"
