modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/ChaoticTrials/ToolSwap/issues"

[[mods]]
modId="${modid}"
version="${mod_version}"
displayName="ToolSwap"
updateJSONURL="https://assets.melanx.de/updates/automatic-tool-swap.json"
displayURL="https://modrinth.com/user/MelanX"
authors="MelanX"
description="""
Swaps the tools to the effective one when it's in hotbar.
"""

[[dependencies.${modid}]]
   modId = "neoforge"
   type = "required"
   versionRange = "[${neo_version},)"
   ordering="NONE"
   side="BOTH"

[[dependencies.${modid}]]
   modId="minecraft"
   type="required"
   versionRange="[${minecraft_version},)"
   ordering="NONE"
   side="BOTH"
